# Generated by scripts/brew_formula.sh - do not edit by hand.
class Maned < Formula
  desc     "Integer-only dataflow language for linear algebra and small ML workloads"
  homepage "https://fabianodicheti.github.io/maned/"
  version  "0.1.0"
  # Free to use for any purpose including commercial, but not redistributable
  # and not open source, so no SPDX identifier describes it.
  license :cannot_represent

  on_macos do
    # One universal tarball covers both Apple Silicon and Intel, so there is no
    # on_arm/on_intel split here.
    url "https://github.com/FabianoDicheti/maned/releases/download/v0.1.0/maned-0.1.0-universal-apple-darwin.tar.gz"
    sha256 "0fd6ffac8e5c3c0b3dd6cfe61e2f015ef86f1080b874ab7217c0803d55889466"
  end

  on_linux do
    on_intel do
      url "https://github.com/FabianoDicheti/maned/releases/download/v0.1.0/maned-0.1.0-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "5003a547761724e111bffc17bdf4d5fbd4d92493a0b34606ca6ae7ca3ec11542"
    end
    on_arm do
      url "https://github.com/FabianoDicheti/maned/releases/download/v0.1.0/maned-0.1.0-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "23ce2f5a5b63b4494970bc18c8744437cc9f976883bc13de7ff202001989af2e"
    end
  end

  def install
    # Homebrew strips the single top-level directory when staging, so the
    # tarball's maned-0.1.0-<target>/bin/ arrives here as bin/.
    bin.install "bin/maned-run", "bin/maned-serve", "bin/maned-lint"
    doc.install "README.md", "LICENSE", "THIRD_PARTY_NOTICES.md"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/maned-run --version")
  end
end
