# Generated by scripts/brew_formula.sh - do not edit by hand.
class Maned < Formula
  desc     "Integer-only dataflow language for linear algebra and small ML workloads"
  homepage "https://fabianodicheti.github.io/maned/"
  version  "0.1.1"
  # Free to use for any purpose including commercial, but not redistributable
  # and not open source, so no SPDX identifier describes it.
  license :cannot_represent

  on_macos do
    # One universal tarball covers both Apple Silicon and Intel, so there is no
    # on_arm/on_intel split here.
    url "https://github.com/FabianoDicheti/maned/releases/download/v0.1.1/maned-0.1.1-universal-apple-darwin.tar.gz"
    sha256 "065d7eb0430362717a7816dd7cacfb10fcea6989329581830bff154365ff30a3"
  end

  on_linux do
    on_intel do
      url "https://github.com/FabianoDicheti/maned/releases/download/v0.1.1/maned-0.1.1-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "41bd4854e30f8cb51355590ce65c23237beba4e1bc12d35804f1a133ab95cd18"
    end
    on_arm do
      url "https://github.com/FabianoDicheti/maned/releases/download/v0.1.1/maned-0.1.1-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "8b9138ab9ccf9027d1c7fd5cf025d9d8d8cbfa0ca918969c041ded0ba5c74bc0"
    end
  end

  def install
    # Homebrew strips the single top-level directory when staging, so the
    # tarball's maned-0.1.1-<target>/bin/ arrives here as bin/.
    bin.install "bin/maned-run", "bin/maned-serve", "bin/maned-lint"
    doc.install "README.md", "LICENSE", "THIRD_PARTY_NOTICES.md"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/maned-run --version")
  end
end
